<?php

namespace Container1EMeoVU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResponseServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Service\ResponseService' shared autowired service.
     *
     * @return \App\Service\ResponseService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/ResponseService.php';

        return $container->services['App\\Service\\ResponseService'] = new \App\Service\ResponseService();
    }
}
