<?php

namespace Container1EMeoVU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserDaoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Dao\UserDao' shared autowired service.
     *
     * @return \App\Dao\UserDao
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Dao/InterfaceDao.php';
        include_once \dirname(__DIR__, 4).'/src/Dao/UserDao.php';

        return $container->services['App\\Dao\\UserDao'] = new \App\Dao\UserDao(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));
    }
}
