doctrine:
    dbal:
        dbname:               promobit
        host:                 127.0.0.1
        port:                 ~
        user:                 root
        password:             190650
        driver:               pdo_mysql        
        override_url: true
        url: '%env(resolve:DATABASE_URL)%'

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
