<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'app_user_index' => [[], ['_controller' => 'App\\Controller\\UserController::index'], [], [['text', '/']], [], []],
    'app_user_postadd' => [[], ['_controller' => 'App\\Controller\\UserController::postAdd'], [], [['text', '/user/add']], [], []],
    'app_user_putupdate' => [[], ['_controller' => 'App\\Controller\\UserController::putUpdate'], [], [['text', '/user/update']], [], []],
    'app_user_postdelete' => [[], ['_controller' => 'App\\Controller\\UserController::postDelete'], [], [['text', '/user/delete']], [], []],
    'app_user_postlogin' => [[], ['_controller' => 'App\\Controller\\UserController::postLogin'], [], [['text', '/user/login']], [], []],
    'app_user_postrestorepass' => [[], ['_controller' => 'App\\Controller\\UserController::postRestorePass'], [], [['text', '/user/restorepass']], [], []],
];
